name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code du repository
      - name: Récupérer le code
        uses: actions/checkout@v4

      # Installer Python
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      # Installer les dépendances Python
      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock

      # Démarrer LocalStack
      - name: Démarrer LocalStack
        run: |
          docker run -d \
            --name localstack \
            -p 4566:4566 \
            localstack/localstack:4.4.0

      # Attendre que LocalStack soit prêt
      - name: Vérifier LocalStack
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:4566/_localstack/health | grep -q '"s3": "available"'; then
              echo "LocalStack est prêt"
              break
            fi

            echo "LocalStack n'est pas encore prêt..."
            sleep 2
          done

      # Créer le bucket S3 de test
      - name: Créer le bucket S3
        run: |
          pip install awscli-local
          awslocal s3 mb s3://automated-backup-system
          awslocal s3 ls

      # Exécuter tous les tests
      - name: Exécuter tous les tests
        run: |
          pytest -v